services:
  inswap:
    image: ion.lc/d1nch8g/inswap
    restart: always
    environment:
      DATABASE: postgresql://user:password@db:5432/db?sslmode=disable

    volumes:
      - ${PWD}:/
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./../data:/var/lib/postgresql/data
