services:
  swap:
    image: ion.lc/d1nch8g/swap
    restart: always
    environment:
      PORT: 80
      DATABASE: postgresql://user:password@db:5432/db?sslmode=disable

    volumes:
      - ${PWD}:/home
    ports:
      - 80:80
      - 443:443
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./../data:/var/lib/postgresql/data
